version: '3'
services:
  local-db:
    image: brainbackdoor/data-subway:0.0.1
    container_name: data_subway_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
      MYSQL_USER: localuser
      MYSQL_PASSWORD: local
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d